# syntax=docker/dockerfile:1

FROM quay.io/jupyter/base-notebook
# jupyter/scipy-notebook, jupyter/datascience-notebook, or jupyter/tensorflow-notebook
# RUN pip install --no-cache-dir matplotlib scikit-learn gensim

RUN pip install --no-cache-dir numpy pandas scipy scikit-learn matplotlib seaborn plotly bokeh statsmodels keras plotly altair xgboost lightgbm nltk spacy beautifulsoup4 requests
RUN pip install --no-cache-dir torch torchvision torchaudio
RUN pip install --no-cache-dir tensorflow

# auto ML - tpot, pycaret, auto-sklearn 
RUN pip install --no-cache-dir pycaret[full] autokeras


